spring:
  data:
    mongodb:
      uri: mongodb+srv://ravipandit20580716:qNVfIUvWGK0MiiOG@cluster0.ozvxacj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: meroJobdb
      auto-index-creation: true

server:
  servlet:
    context-path: /merojob
